export type OfferType = "STAY" | "DINING" | "PACKAGE";

export interface Offer {
  id: string;
  slug: string;
  title: string;
  shortDescription: string;
  description?: string;
  type: OfferType;
  image: string;
  originalPrice?: number;
  offerPrice?: number;
  discountPercentage?: number;
  currency?: string;
  accommodationId?: string;
  diningItemId?: string;
  startDate?: string;
  endDate?: string;
  active: boolean;
  featured?: boolean;
}

export type AmenityKey = "breakfast" | "veranda" | "garden" | "air" | "family" | "bed";

export interface Accommodation {
  id: string;
  slug: string;
  name: string;
  roomSize: string;
  shortDescription: string;
  fullDescription: string;
  heroImage: string;
  images: string[];
  amenities: [AmenityKey, string][];
  capacity?: number;
  bedType?: string;
  highlights?: string[];
  details?: [string, string][];
}

export interface DiningItem {
  id: string;
  slug: string;
  name: string;
  description: string;
  image: string;
  category: string;
  price?: number;
  currency?: string;
  available: boolean;
  featured?: boolean;
  dietary?: string[];
}

export interface MenuItem {
  id: string;
  slug: string;
  name: string;
  description: string;
  category: string;
  image: string;
  price?: number;
  currency?: string;
  available: boolean;
  featured?: boolean;
  dietary?: string[];
  highlights?: string[];
}

export interface BookingRequest {
  accommodationId: string;
  offerId?: string;
  guestName: string;
  email: string;
  phone: string;
  checkIn: string;
  checkOut: string;
  adults: number;
  children: number;
  specialRequests?: string;
}

export interface RestaurantReservationRequest {
  offerId?: string;
  guestName: string;
  phone: string;
  email: string;
  date: string;
  time: string;
  guests: number;
  specialRequests?: string;
}

export interface OrderItemInput {
  menuItemId: string;
  quantity: number;
  notes?: string;
}

export interface OrderRequest {
  offerIds?: string[];
  items: OrderItemInput[];
  customerName: string;
  phone: string;
  email: string;
  specialInstructions?: string;
  orderMethod: "WHATSAPP" | "ONLINE";
  billingAddress?: { address: string; city: string; country: string };
}

export interface OrderItem extends OrderItemInput {
  name: string;
  unitPrice: number;
}

export type OrderType = "DINE_IN" | "TAKEAWAY" | "DELIVERY";

export type OrderStatus = "PENDING" | "CONFIRMED" | "PREPARING" | "READY" | "COMPLETED" | "CANCELLED";

export interface RestaurantOrder {
  id: string;
  orderNumber: string;
  customerName: string;
  phone: string;
  email: string;
  items: OrderItem[];
  specialInstructions?: string;
  orderType?: OrderType;
  subtotal: number;
  discount: number;
  total: number;
  currency: string;
  orderMethod: "WHATSAPP" | "ONLINE";
  paymentMethod: "WHATSAPP" | "PAYHERE";
  orderStatus: OrderStatus;
  paymentStatus: PaymentStatus;
  createdAt: string;
  version: number;
  canRetryPayment: boolean;
}

/** Signed checkout values are generated by the backend, never by the browser. */
export interface PayHerePayment {
  sandbox: boolean;
  merchant_id: string;
  return_url: string;
  cancel_url: string;
  notify_url: string;
  order_id: string;
  items: string;
  currency: string;
  amount: string;
  first_name: string;
  last_name: string;
  email: string;
  phone: string;
  address: string;
  city: string;
  country: string;
  hash: string;
}

export interface PreparedOrder {
  order: RestaurantOrder;
  accessToken: string;
  payment?: PayHerePayment;
}

export type BookingStatus = "PENDING" | "CONFIRMED" | "CANCELLED";
export type PaymentStatus = "UNPAID" | "PENDING" | "PAID" | "FAILED" | "REFUNDED";

export interface ApiResult<T = undefined> {
  success: boolean;
  message?: string;
  reference?: string;
  data?: T;
}

export type ApiStatus = "idle" | "loading" | "success" | "error";

export type ReviewStatus = "PENDING" | "APPROVED" | "REJECTED";

export interface GuestReview {
  id: string;
  name: string;
  email?: string;
  country?: string;
  rating: number;
  comment: string;
  status: ReviewStatus;
  active?: boolean;
  createdAt: string;
}
