// DEMO DATA for the FESTHER Admin Panel (UI phase only).
// Replace with a REST API / Firebase-backed store later without touching the UI.
import type {
  AdminGalleryImage,
  AdminOffer,
  GalleryCategory,
  ReviewComment,
} from "./types";
import type { RestaurantOrder } from "@/lib/types";

const u = (id: string, w: number, h: number) =>
  `https://images.unsplash.com/${id}?q=80&w=${w}&h=${h}&fit=crop&auto=format`;

export const galleryCategories: GalleryCategory[] = [
  "ROOMS",
  "VIEWS",
  "DINING",
  "SPACES",
  "WELLNESS",
];

export const sampleGalleryImages: AdminGalleryImage[] = [
  {
    id: "img-1001",
    src: u("photo-1590490360182-c33d57733427", 1100, 1400),
    title: "A room made for unhurried mornings",
    alt: "Soft morning light inside a hotel room",
    category: "ROOMS",
    description: "The Garden Suite at first light — linen, open air and a slow start to the day.",
    createdAt: "2026-08-12",
  },
  {
    id: "img-1002",
    src: u("photo-1571003123894-1f0594d2b5d9", 1400, 950),
    title: "Quiet corners, warm light",
    alt: "Reading corner with warm lamp light",
    category: "ROOMS",
    description: "A considered corner for reading and rest, finished in local wood.",
    createdAt: "2026-08-18",
  },
  {
    id: "img-1003",
    src: u("photo-1582719471384-894fbb16e074", 1100, 1600),
    title: "Thoughtful details of the stay",
    alt: "Bedside details in a boutique hotel bedroom",
    category: "ROOMS",
    description: "Small details — brass, linen and island craft — that make a stay memorable.",
    createdAt: "2026-08-21",
  },
  {
    id: "img-1004",
    src: u("photo-1618773928121-c32242e63f39", 1400, 1400),
    title: "Slow mornings in bed",
    alt: "Hotel bedroom with white bedding in morning light",
    category: "ROOMS",
    description: "Breakfast trays, open curtains and no rush at all.",
    createdAt: "2026-09-02",
  },
  {
    id: "img-1005",
    src: u("photo-1546708973-b339540b5162", 1500, 850),
    title: "Journeys through the island",
    alt: "Misty green mountains of Sri Lanka",
    category: "VIEWS",
    description: "The central highlands rolling out below the estate.",
    createdAt: "2026-07-30",
  },
  {
    id: "img-1006",
    src: u("photo-1469474968028-56623f02e42e", 1400, 950),
    title: "The island below",
    alt: "Coastal view from a high vantage point",
    category: "VIEWS",
    description: "Where the garden meets the horizon.",
    createdAt: "2026-08-05",
  },
  {
    id: "img-1007",
    src: u("photo-1507525428034-b723cf961d3e", 1500, 900),
    title: "Warm sand, calm sea",
    alt: "Calm beach shoreline at dusk",
    category: "VIEWS",
    description: "The southern coast, quiet in the late afternoon.",
    createdAt: "2026-08-09",
  },
  {
    id: "img-1008",
    src: u("photo-1448375240586-882707db888b", 1100, 1600),
    title: "Green that goes on and on",
    alt: "Lush green forest canopy",
    category: "VIEWS",
    description: "Ceylon tea country, endless and green.",
    createdAt: "2026-08-14",
  },
  {
    id: "img-1009",
    src: u("photo-1501785888041-af3ef285b470", 1400, 950),
    title: "Still mornings, open skies",
    alt: "Open sky over a calm landscape",
    category: "VIEWS",
    description: "Clear skies over the estate gardens.",
    createdAt: "2026-08-22",
  },
  {
    id: "img-1010",
    src: u("photo-1414235077428-338989a2e8c0", 1400, 950),
    title: "A table set just for you",
    alt: "Fine dining table setting with candles",
    category: "DINING",
    description: "The dining room laid out for an evening set menu.",
    createdAt: "2026-08-26",
  },
  {
    id: "img-1011",
    src: u("photo-1504674900247-0877df9cc836", 1300, 1300),
    title: "Flavours of the island",
    alt: "Plated dish with island ingredients",
    category: "DINING",
    description: "Seasonal produce, presented simply and honestly.",
    createdAt: "2026-09-01",
  },
  {
    id: "img-1012",
    src: u("photo-1533089860892-a7c6f0a88666", 1400, 950),
    title: "Breakfast, unhurried",
    alt: "Breakfast table with fruit and coffee",
    category: "DINING",
    description: "A long breakfast on the verandah.",
    createdAt: "2026-09-04",
  },
  {
    id: "img-1013",
    src: u("photo-1517248135467-4c7edcad34c4", 1100, 1400),
    title: "Evenings in good company",
    alt: "Guests dining together in warm light",
    category: "DINING",
    description: "Shared tables, longer evenings.",
    createdAt: "2026-09-07",
  },
  {
    id: "img-1014",
    src: u("photo-1600585154340-be6161a56a0c", 1500, 900),
    title: "Indoor and outdoor, together",
    alt: "Hotel terrace merging indoor and outdoor",
    category: "SPACES",
    description: "Architecture that lets the garden drift indoors.",
    createdAt: "2026-09-09",
  },
  {
    id: "img-1015",
    src: u("photo-1512917774080-9991f1c4c750", 1400, 1400),
    title: "Architecture in the landscape",
    alt: "Modern resort building in the landscape",
    category: "SPACES",
    description: "Low lines, natural materials, the landscape doing the rest.",
    createdAt: "2026-09-11",
  },
  {
    id: "img-1016",
    src: u("photo-1466781783364-36c955e42a7f", 1400, 950),
    title: "Paths into the green",
    alt: "Garden path winding through greenery",
    category: "SPACES",
    description: "Wandering paths through the estate gardens.",
    createdAt: "2026-09-12",
  },
  {
    id: "img-1017",
    src: u("photo-1544161515-4ab6ce6db874", 1100, 1500),
    title: "Time to slow the breath",
    alt: "Wellness treatment in soft light",
    category: "WELLNESS",
    description: "The spa — quiet, calm and unhurried.",
    createdAt: "2026-09-13",
  },
  {
    id: "img-1018",
    src: u("photo-1540555700478-4be289fbecef", 1100, 1600),
    title: "Quiet, unhurried care",
    alt: "Relaxing wellness scene with towels and oils",
    category: "WELLNESS",
    description: "Essential oils, warm towels and a slower pace.",
    createdAt: "2026-09-14",
  },
  {
    id: "img-1019",
    src: u("photo-1611892440504-42a792e24d32", 1500, 850),
    title: "The pool at golden hour",
    alt: "Resort pool glowing at sunset",
    category: "WELLNESS",
    description: "Laps and long floats as the light turns gold.",
    createdAt: "2026-09-15",
  },
  {
    id: "img-1020",
    src: u("photo-1520250497591-112f2f40a3f4", 1400, 950),
    title: "Cool water, warm days",
    alt: "Pool water surface with warm sunlight",
    category: "WELLNESS",
    description: "The saltwater pool under a hot island sun.",
    createdAt: "2026-09-16",
  },
];

export const sampleComments: ReviewComment[] = [
  {
    id: "c-2001",
    name: "Isabella Perera",
    comment: "The most peaceful stay we have had in Sri Lanka. The garden suite and the breakfasts are simply beautiful.",
    rating: 5,
    date: "2026-09-15",
    status: "approved",
  },
  {
    id: "c-2002",
    name: "Daniel Fernando",
    comment: "Wonderful hospitality from arrival to departure. The pool at sunset is unforgettable.",
    rating: 5,
    date: "2026-09-12",
    status: "approved",
  },
  {
    id: "c-2003",
    name: "Emily Carter",
    comment: "Second time visiting and it does not disappoint. The evening set dinner was superb.",
    rating: 4,
    date: "2026-09-08",
    status: "pending",
  },
  {
    id: "c-2004",
    name: "Arjun Mehta",
    comment: "Great rooms and staff, though check-in took a little longer than expected.",
    rating: 4,
    date: "2026-09-05",
    status: "approved",
  },
  {
    id: "c-2005",
    name: "Sofia Rossi",
    comment: "The estate walks and the wellness session made our honeymoon feel truly special.",
    rating: 5,
    date: "2026-08-30",
    status: "approved",
  },
  {
    id: "c-2006",
    name: "Tom Whitfield",
    comment: "Beautiful property but the dining room was a bit busy during dinner hours.",
    rating: 3,
    date: "2026-08-27",
    status: "pending",
  },
  {
    id: "c-2007",
    name: "Nadia Hassan",
    comment: "Loved everything — the tea tastings, the gardens and the staff's warmth.",
    rating: 5,
    date: "2026-08-22",
    status: "approved",
  },
  {
    id: "c-2008",
    name: "Lucas Meyer",
    comment: "Nice stay overall. WiFi in the rooms could be more reliable.",
    rating: 3,
    date: "2026-08-18",
    status: "hidden",
  },
  {
    id: "c-2009",
    name: "Priya Raman",
    comment: "An elegant escape with thoughtful touches everywhere. Highly recommend the package.",
    rating: 5,
    date: "2026-08-11",
    status: "approved",
  },
  {
    id: "c-2010",
    name: "James O'Brien",
    comment: "",
    rating: 1,
    date: "2026-08-02",
    status: "hidden",
  },
];

export const sampleOffers: AdminOffer[] = [
  {
    id: "off-3001",
    title: "Romantic Getaway",
    shortDescription: "Two quiet nights in the Garden Suite with breakfast, evening dining and time for two.",
    fullDescription:
      "An intimate escape in the Garden Suite. Two nights with daily breakfast on your private verandah, a candlelit set dinner prepared by our chefs and calm, slow mornings among the gardens.",
    image: "/images/accommodation/room-1.jpg",
    originalPrice: 48000,
    offerPrice: 40800,
    discount: 15,
    startDate: "2026-10-01",
    endDate: "2027-03-31",
    type: "ACCOMMODATION",
    status: "active",
    cta: "BOOK_NOW",
    createdAt: "2026-08-01",
  },
  {
    id: "off-3002",
    title: "Weekend Escape",
    shortDescription: "Two nights in the Deluxe Room with breakfast, pool and gardens.",
    fullDescription:
      "A two-night escape in the Deluxe Room with daily breakfast, access to the pool and gardens, and a relaxed, considered rhythm from arrival to departure.",
    image: "/images/accommodation/room-3.jpg",
    originalPrice: 32000,
    offerPrice: 27000,
    discount: 16,
    startDate: "2026-10-01",
    endDate: "2027-03-31",
    type: "ACCOMMODATION",
    status: "inactive",
    cta: "BOOK_NOW",
    createdAt: "2026-08-01",
  },
  {
    id: "off-3003",
    title: "Extended Stay",
    shortDescription: "Five nights in the Garden Suite at a calm, gentle rate.",
    fullDescription:
      "Five nights in the Garden Suite with daily breakfast and a ten percent rate that settles in as you do. Ideal for slow travellers and long weekends.",
    image: "/images/accommodation/room-2.jpg",
    originalPrice: 78000,
    offerPrice: 66500,
    discount: 15,
    startDate: "2026-11-01",
    endDate: "2027-04-30",
    type: "ACCOMMODATION",
    status: "active",
    cta: "BOOK_NOW",
    createdAt: "2026-08-05",
  },
  {
    id: "off-3004",
    title: "A Taste of Sri Lanka",
    shortDescription: "A five-course island tasting menu with wine pairing.",
    fullDescription:
      "A five-course tasting menu built around seasonal island produce, served with a wine pairing and tea service on the verandah.",
    image: u("photo-1504674900247-0877df9cc836", 1200, 900),
    originalPrice: 12000,
    offerPrice: 9000,
    discount: 25,
    startDate: "2026-10-01",
    endDate: "2027-03-31",
    type: "DINING",
    status: "active",
    cta: "ORDER_NOW",
    createdAt: "2026-08-10",
  },
  {
    id: "off-3005",
    title: "Dinner for Two",
    shortDescription: "An intimate candlelit set dinner for two in the dining room.",
    fullDescription:
      "A candlelit set dinner prepared by our chefs for two — starter, main and dessert with island tea service. The perfect way to close a slow day.",
    image: u("photo-1414235077428-338989a2e8c0", 1200, 900),
    originalPrice: 16000,
    offerPrice: 13600,
    discount: 15,
    startDate: "2026-10-01",
    endDate: "2027-03-31",
    type: "DINING",
    status: "inactive",
    cta: "ORDER_NOW",
    createdAt: "2026-08-10",
  },
  {
    id: "off-3006",
    title: "The Complete Escape",
    shortDescription: "Garden Suite, tasting dinner and a wellness session in one package.",
    fullDescription:
      "Three nights in the Garden Suite, the island tasting menu for two and a wellness session each — the full FESTHER experience in one considered package.",
    image: "/images/accommodation/room-1.jpg",
    originalPrice: 95000,
    offerPrice: 79500,
    discount: 16,
    startDate: "2026-10-01",
    endDate: "2027-03-31",
    type: "PACKAGES",
    status: "active",
    cta: "BOOK_NOW",
    createdAt: "2026-08-15",
  },
  {
    id: "off-3007",
    title: "Wintersun at FESTHER",
    shortDescription: "Garden Suite nights with daily breakfast through the winter season.",
    fullDescription:
      "Long, warm days and cool evenings — special winter rates on the Garden Suite with daily breakfast and a complimentary afternoon tea service.",
    image: "/images/accommodation/room-4.jpg",
    originalPrice: 54000,
    offerPrice: 45900,
    discount: 15,
    startDate: "2026-12-01",
    endDate: "2027-02-28",
    type: "SEASONAL",
    status: "active",
    cta: "BOOK_NOW",
    createdAt: "2026-09-01",
  },
  {
    id: "off-3008",
    title: "Harvest Table",
    shortDescription: "A seasonal celebration dinner menu for the autumn harvest.",
    fullDescription:
      "A celebration of the harvest — a special four-course dinner featuring the season's best island produce, available through the autumn.",
    image: u("photo-1533089860892-a7c6f0a88666", 1200, 900),
    originalPrice: 8500,
    offerPrice: 6800,
    discount: 20,
    startDate: "2026-10-15",
    endDate: "2026-12-20",
    type: "SEASONAL",
    status: "inactive",
    cta: "ORDER_NOW",
    createdAt: "2026-09-05",
  },
];

export const sampleRestaurantOrders: RestaurantOrder[] = [
  {
    id: "ord-1001",
    orderNumber: "FES-00101",
    customerName: "Manuja Perera",
    email: "manuja@example.com",
    phone: "0771234567",
    items: [
      { menuItemId: "devilled-prawns", name: "Devilled Prawns", quantity: 2, unitPrice: 3500 },
      { menuItemId: "pol-roti-sambols", name: "Pol Roti & Sambols", quantity: 1, unitPrice: 2500 },
    ],
    specialInstructions: "Less spicy please.",
    subtotal: 9500,
    discount: 0,
    total: 9500,
    currency: "LKR",
    orderMethod: "WHATSAPP",
    paymentMethod: "WHATSAPP",
    orderStatus: "CONFIRMED",
    paymentStatus: "UNPAID",
    createdAt: "2026-09-18T18:40:00.000Z",
    version: 2,
    canRetryPayment: false,
  },
  {
    id: "ord-1002",
    orderNumber: "FES-00102",
    customerName: "Amaya Fernando",
    email: "amaya@example.com",
    phone: "0759876543",
    items: [
      { menuItemId: "signature-dining-menu", name: "Signature Dining Menu", quantity: 1, unitPrice: 9000 },
    ],
    specialInstructions: "Vegetarian platter, no prawns.",
    subtotal: 9000,
    discount: 0,
    total: 9000,
    currency: "LKR",
    orderMethod: "ONLINE",
    paymentMethod: "PAYHERE",
    orderStatus: "COMPLETED",
    paymentStatus: "PAID",
    createdAt: "2026-09-17T12:15:00.000Z",
    version: 4,
    canRetryPayment: false,
  },
  {
    id: "ord-1003",
    orderNumber: "FES-00103",
    customerName: "Dilshan Wickramasinghe",
    email: "dilshan@example.com",
    phone: "0761112233",
    items: [
      { menuItemId: "kottu-roti", name: "Kottu Roti", quantity: 1, unitPrice: 1800 },
      { menuItemId: "king-coconut-water", name: "King Coconut Water", quantity: 2, unitPrice: 600 },
    ],
    subtotal: 3000,
    discount: 0,
    total: 3000,
    currency: "LKR",
    orderMethod: "ONLINE",
    paymentMethod: "PAYHERE",
    orderStatus: "PREPARING",
    paymentStatus: "PAID",
    createdAt: "2026-09-18T19:05:00.000Z",
    version: 2,
    canRetryPayment: false,
  },
  {
    id: "ord-1004",
    orderNumber: "FES-00104",
    customerName: "Ishara Gunawardena",
    email: "ishara@example.com",
    phone: "0788899000",
    items: [
      { menuItemId: "devilled-prawns", name: "Devilled Prawns", quantity: 1, unitPrice: 3500 },
      { menuItemId: "prawn-curry", name: "Prawn Curry", quantity: 1, unitPrice: 4200 },
    ],
    specialInstructions: "Extra mild.",
    subtotal: 7700,
    discount: 770,
    total: 6930,
    currency: "LKR",
    orderMethod: "ONLINE",
    paymentMethod: "PAYHERE",
    orderStatus: "PENDING",
    paymentStatus: "PENDING",
    createdAt: "2026-09-19T08:22:00.000Z",
    version: 1,
    canRetryPayment: true,
  },
];